matrix:
- name: Markdown
  # use aspell british english dictionary 
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    #additional words not included in the general dictionary
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  #ignore urls 
  - pyspelling.filters.url:
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
        # ignore tags
        - open: '.. _'
          close: ':'
        # ignore images
        - open: /figure/
          close: /center/

  sources:
  # runs on the docs files
  - 'docs/**/*.rst'
  default_encoding: utf-8
