matrix:
- name: Markdown
  # use aspell british english dictionary 
  aspell:
    lang: en
    d: en_GB
  dictionary:
    wordlists:
    #additional words not included in the general dictionary
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  #ignore urls 
  - pyspelling.filters.url:
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
        # ignore tags
        - open: '.. _'
          close: ':'
        # ignore reStructuredText toctree
113      - open: '\.\.\s+toctree::'
114        close: '(?P<toctree>(?:((?P<indent>[ ]+).*$)|(\n))+)'
115     # ignore directives
116      - open: '\.\.\s+(figure|include)::'
117        close: '$'

  sources:
  # runs on the docs files
  - 'docs/**/*.rst'
  default_encoding: utf-8
