name: Docs build
on: [push, pull_request]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'true'
    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: 3.11
        architecture: x64
    - run: pip install -r requirements.txt
    - run: cd ./docs/ && make dirhtml
    - run: cd ./docs/ && make linkcheck
