name: Spellcheck Action
on: [push, pull_request]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v6
    - uses: rojopolis/spellcheck-github-actions@v0
      name: Spellcheck
